import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar";
import GlobalState from "@/context/GlobalContext";
import Footer from "@/components/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Icchapurti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} flex flex-col min-h-screen`}>
        <GlobalState>
          <Navbar />
          <div className="flex-grow">
            {children}
          </div>
          <Footer />
        </GlobalState>
        <Toaster />
      </body>
    </html>
  );
}
